In [1]:
import pandas as pd
import numpy as np

In [3]:
a = np.array

In [17]:
c1 = 36
c2 = -15
c3 = -3

In [18]:
v1 = a([2,1])
v2 = a([3,2])
v3 = a([1,2])

In [19]:
(c1 * v1) + (c2 * v2) + (c3 * v3)

array([24,  0])

In [20]:
(c1 * v1)

array([72, 36])

In [21]:
(c2 * v2)

array([-45, -30])

In [22]:
(c3 * v3)

array([-3, -6])

In [23]:
c1 = -4
c2 = 3
c3 = -1

In [24]:
v1 = a([2,1])
v2 = a([3,2])
v3 = a([1,2])

In [25]:
(c1 * v1) + (c2 * v2) + (c3 * v3)

array([0, 0])